const STATES = Object.freeze({
  LOBBY: 'LOBBY',
  QUESTION_ACTIVE: 'QUESTION_ACTIVE',
  COLLECT: 'COLLECT',
  REVEAL: 'REVEAL',
  LEADERBOARD: 'LEADERBOARD',
  GAME_END: 'GAME_END',
});

const TRANSITIONS = {
  [STATES.LOBBY]: new Set([STATES.QUESTION_ACTIVE]),
  [STATES.QUESTION_ACTIVE]: new Set([STATES.COLLECT]),
  [STATES.COLLECT]: new Set([STATES.REVEAL]),
  [STATES.REVEAL]: new Set([STATES.LEADERBOARD]),
  [STATES.LEADERBOARD]: new Set([STATES.QUESTION_ACTIVE, STATES.GAME_END]),
  [STATES.GAME_END]: new Set([STATES.LOBBY]),
};

function canTransition(from, to) {
  return Boolean(TRANSITIONS[from]?.has(to));
}

module.exports = {
  STATES,
  TRANSITIONS,
  canTransition,
};
